### ISSUE TITLE
Game does not start when upgrading ImageSharp to 1.0.0-beta0007

### ISSUE THREAD

**Issue by matyasforian** [mellinoe/Snake#1]
this is the exception:

```
Unhandled exception. System.MissingMethodException: Method not found: 'SixLabors.ImageSharp.Image`1<SixLabors.ImageSharp.PixelFormats.Rgba32> SixLabors.ImageSharp.Image.Load(Syst
em.String)'.
   at Veldrid.ImageSharp.ImageSharpTexture..ctor(String path, Boolean mipmap)
   at Snake.SpriteRenderer.Load(GraphicsDevice gd, String spriteName) in C:\CODE\kestrel\kestrel-desktop\SpriteRenderer.cs:line 97
   at Snake.SpriteRenderer.Draw(GraphicsDevice gd, CommandList cl) in C:\CODE\kestrel\kestrel-desktop\SpriteRenderer.cs:line 141
   at Snake.Program.DrawFrame() in C:\CODE\kestrel\kestrel-desktop\Program.cs:line 109
   at Snake.Program..ctor() in C:\CODE\kestrel\kestrel-desktop\Program.cs:line 81
   at Snake.Program.Main(String[] args) in C:\CODE\kestrel\kestrel-desktop\Program.cs:line 37
```

with beta-006 it works fine.

**Comment by matyasforian** [comment]
Its a Veldrid bug, I'll file it there.
